name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate schemas
      run: python -m bsmschema specification/schema/
    - name: Build
      run: jb build -W specification
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: ./specification/_build/html
